### ISSUE TITLE
Describing the resulting data

### ISSUE THREAD

**Issue by Sicheng2000** [Sicheng2000/lab-05#1]
@francojc.
Professor Francom, I'm not entirely clear on your requirement to "Include a section to describe the resulting data." Does this mean I should filter and arrange my data after acquiring it? I'm finding it challenging to determine the appropriate approach, especially since I was using Switchboard-1 Release 2, which contains HTML and a series of .utt files, rather than our previous CSV file. How can I effectively filter and arrange this data to present it clearly? Your guidance would be greatly appreciated.

Thank you!

**Comment by francojc** [comment]
No, the idea is simply to create a Data origin file which describes the data. See the textbook and the recipe for information as to what to include in the Data origin file.
